# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9827a84964cd139e9c05e30f35c65b99270edbae5de82d19f411e2f8eb1f22ad23305ec18715042c617ccc694b051ea96413567c8f828e513f2cb9ae1fc5214

test:
  secret_key_base: a007101e8d23e40a6aca16747670ab2b33ba89d59aa0b22655d2d050f5a526328a2c88180f2cbd0ddaea7adeb385e9e219e93ab8b92f6aff11ac4c135f2514cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
